# load_packages.R

###############################################################################
# This code loads my most used packahes and sets the degault ggplot2 theme
# to cowpulot.
###############################################################################

suppressMessages( library( tidyverse ) )    # I live in the tidyverse ...
suppressMessages( library( lubridate ) )    # For powerful date processing ...
suppressMessages( library( readr ) )        # For csv data input ...
suppressMessages( library( readxl ) )       # To read Excel spreadsheets ...
suppressMessages( library( purrr ) )        # To allow functional 
                                            # for modern programming ...
suppressMessages( library( glue ))          # A tidyverse improvement to paste ...                                                # loops ...
suppressMessages( library( Hmisc ))         # To impute missing values ...
suppressMessages( library( stringr ) )      # Consistent string functions ...
suppressMessages( library( modelr ) )       # Regression support packages ...
suppressMessages( library( broom ) )        # Converts regression output to
                                            # tidy data ...
suppressMessages( library( moderndive ) )   # Provides updated functions 
                                            # to access regressions ...
suppressMessages( library( GGally ) )            # For scatter plot matrix ...
suppressMessages( library( Hmisc ) )        # For data imputation ...
suppressMessages( library( flextable ) )    # For nice table output ...
suppressMessages( library( officer ) )      # For extensions to flextble 
                                            # Microsft Word ...
suppressMessages( library( latex2exp ) )    # Converts laytec notation to
                                            # R mathemtical exprressions ...
suppressMessages( library( cowplot ))       # For more profesional graphics ...
