---
title: "0010_plan_walks"
author: "adopted by Craig W. Slinkman"
date: "6/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Purpose of this R-Markdown document

The purpose of this document is to plan the next walk.  It is cone by sorting the active walks by the last date that a route was walked.

```{r load_packages}

###########################################################################
# We load the packages used by MyWalks.  This is a source file in the 
# MyWalks function sub-directory.
###########################################################################

suppressMessages( require(tidyverse))       # I live in the tidyverse ...
suppressMessages( require(flextable))       # For professional tables ...
```


```{r load_functions, echo=FALSE }
###########################################################################
# We load the functions we need to plan the walks.
###########################################################################

source("D:/R-Projects/MyWalks/functions/get_day_routes.R")
```




```{r}
###########################################################################
# We load the functions that are required for this R-Markdown document.
###########################################################################

all_day_routes <- get_day_routes()

```


```{r filyter_out_non_walking_days, echo=FALSE}

###########################################################################
# Keep only days when a walk occurred.
###########################################################################

only_walks <-
    all_day_routes %>% 
        filter( walked == 1 )
```


```{r keep_active_routes_only}
###########################################################################
# Filter out all walks that are not active.
###########################################################################

active_route_walks <- 
    only_walks %>% 
        filter( active == 1)

```


## Display walk schedule

The walks schedule displays the desired walking schedule in reverse order]
with the oldest walks being listed first.  

```{r group_by_route_and find last_walk}

###########################################################################
# Select the walks within each route that have the maximum (latest) walk
# date.
###########################################################################
schedule <- 
    active_route_walks %>% 
        group_by( route ) %>% 
            arrange( route, date_time ) %>% 
                slice_max( date_time )

###########################################################################
# For each active route compute the mean distance and mean time to walk.
###########################################################################



###########################################################################
# Prepare the data for the flextable report.
###########################################################################
           
schedule %>%
    mutate( date = as.Date( date_time )) %>% 
    arrange( date ) %>% 
        select( route, date ) %>%
            flextable() %>% 
                width( j = 1, 3 ) %>% 
                width( j = 2, 3 )
        
```

