---
title: "Last 007 days walks"
author: "adopted by Craig W. Slinkman"
date: "6/16/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## R Markdown
the R-Markdown document lists the last 7 days walk activity and provides a summary of the last 7 days.

```{r load_packages, echo=FALSE}

###########################################################################
# We load necessary packages to supply needed functionality.
###########################################################################

suppressMessages(library(tidyverse))   # I live in the tidyverse ...
suppressMessages(library(readxl))      # To read an xlsx spreadsheet ...
suppressMessages(library(lubridate))   # For advanced date processing ...
suppressMessages(require(flextable))   # For reporting ...
suppressMessages(require(cowplot))     # For professional plots ...
```   



```{r set_cowplot_to_default_theme}

###########################################################################
# We make cowplot the default theme for this document.
###########################################################################
theme_set( theme_cowplot )
```

```{r define_functions}
source('~/R-Projects/MyWalks/functions/get_day_routes.R')
source('~/R-Projects/MyWalks/functions/compute_parametrics.R')

```

```{r read_data}
all_walks <- get_day_routes()
```

```{r keep_the_last_007_days_data}

############################################################################
# Determine the date of the first walk to be analysed.
############################################################################

first_date <- date( now()) - 7

############################################################################# Add plain date and chr_day for reporting.
###########################################################################

temp_tibble <-    
    all_walks  %>% 
        mutate( date = date( date_time ),
                chr_day = wday( date_time,
                                label = TRUE,
                                abbr = TRUE,
                                week_start = 
                                getOption("lubridate.week.start", 7)))


###########################################################################
# Sort id descending order ny date_time and select variables needed for 
# report.
############################################################################

last_007_days_walks <- 
    temp_tibble %>% 
        filter( date > first_date ) %>% 
            arrange( desc( date_time  )) 
                    
```

```{r summarize_last_007_days_walks}

############################################################################
# We compute the totals (when they make sense), the means, the standard
# deviations, the coefficient of variation, the skewness, and the kurosis
# of the basic walking statistics for the last 7 days walks.
###########################################################################

summary <- compute_parametrics( last_007_days_walks )
```

## Last seven days walks 

```{r list_last_007_days}

   last_007_days_walks %>%
            select( walked,
                    date,
                    missed_reason,
                    route,
                    miles,
                    steps,
                    hours,
                    pace,
                    gain,
                    kcal,
                    avg_hr,
                    max_hr,
                    breaks,
                    shuffles ) %>% 
                flextable() %>% 
                    width( j = c( 2, 4), 1.50 ) %>% 
                    width( j = 3, 2.50 ) %>% 
                    colformat_num( j = 5:8,
                                   digits = 2,
                                   na_str = "" ) %>% 
                    colformat_num( j = c( 9, 10:14 ),
                                   digits = 0,
                                   na_str = "" ) %>% 
                   colformat_num(  j = 9, 
                                   digits = 3,
                                   na_str = "" ) %>% 
                set_header_labels( "Walked" = "walks") %>% 
                theme_zebra()
                   

```

### Summary report

```{r}

###########################################################################
# We create print the summary report here using flextable.
###########################################################################

summary %>% 
    flextable() %>% 
        width( j = 1, 2.0 ) %>% 
        colformat_int( j = 2,
                       na_str = "" ) %>% 
        colformat_num( j = 3:13,
                       digits = 2,
                       na_str = "" ) 
      
                      
```

