---
title: "Walks Analysis: Categorical variables"
author: "by Craig W. Slinkman"
date: "July 23, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r set_control_variables}
#
use_Imputed_missing_values <- FALSE               # Shoud this script read the imputed
                                                 # imputed missing variables files ...
#
```



```{r load_packages, echo=FALSE}
#
source( "functions/load_libraries_v003.R" )
#
```

```{r load_functions}
#
source('~/R-Projects/Rsource/compute_dates_v003.R')        # Compute useful dates ...
#
```


```{r display_period, echo=FALSE}
#

format_date <-                                   # Function to format dates 
    function( unformated_date ){
        format( unformated_date, "%Y-%m%-%d" )
    } 
        
dates          <- compute_dates()                          # Compute dates ...
date_current   <- dates$date_000_days_ago                  # Access current date ...
date_partition <- dates$date_180_days_ago + 1              # Compute partition          
                                                           # date ...
#
```

```{r get_data}
#
file_path <- file.path( "data",
                        "imputed_walks.rds" )             # Set file path ... 
load( file_path )
# 
```




