---
title: "Walks Analysis: Categorical variables"
author: "by Craig W. Slinkman"
date: "July 23, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r set_control_variables}
#


#
```



```{r load_packages, echo=FALSE}
#
source( "functions/load_libraries_v003.R" )
#
```

```{r load_functions}
#
source('~/R-Projects/Rsource/compute_dates_v004.R')        # To compute dates ...
source('functions/display_selected_days_v001.R')           # To d splay days  ...
#
library( grid )                                   # This packages enable use to display
library( gridExtra )                              # small tables with graphic output
#
```


```{r display_period, echo=FALSE}
#

format_date <-                                   # Function to format dates 
    function( unformated_date ){
        format( unformated_date, "%Y-%m%-%d" )
    } 
        
dates          <- compute_dates()                          # Compute dates ...
date_current   <- dates$date_000_days_ago                  # Access current date ...
date_partition <- dates$date_180_days_ago + 1              # Compute partition          
                                                           # date ...
#
```

```{r get_data}
#
file_path <- file.path( "data",                           # Set file path ...
                        "imputed_days.rds" ) 
#
load( file_path )                                         # Load days object ...
# 
```

### Display dFirst 10 observation inn last 180 days 

#### First 10 observations

```{r display_first_10}

days <- imputed_days[ 1:10, c(1,2,6:14)]                  # First 10 observations in
                                                          # last 180 days ...
display_selected_days( days )
            
    


```

#### Last 10 days of the last 180 days 


```{r display_last_10_days}
#
to <- dim( imputed_days )[1]                  # Number of last row ...
from <- to - 10 + 1                           # Number of 10 rows drom to ...

days <- imputed_days[ from:to, c(1,2,6:14)] 

display_selected_days( days )                 # Display as flextable ...

days <- imputed_days[ from:to, c(1,2,6:14)]
```
 
### Days walked and missed 

```{r plot_barchars_od Missed_walks and walks}
#


to   <- dim( imputed_days )[1]
from <- to - 180 + 1

days <- imputed_days[from:to, c(1,2,6:14)]

y_scale = seq( from=0,to=180, by=10 )
y_labels = y_scale

days %>% 
    mutate( Walked = ifelse( walked == 1,
                             "Yes", "No")) %>% 
    ggplot( aes( x = Walked )) + 
        geom_bar( color="blue",
                  fill="yellow" ) +
        geom_text(stat='count', 
                  aes(label=..count..), vjust=-1) +
    scale_y_continuous( "Frequency",
                        breaks = y_scale,
                        labels= y_scale) +
    coord_cartesian(ylim=c(0, 180))
#
```


### Reasons for days without walks 

```{r draw_parchart_of_reasons_for_no_walks}
#
y_scale <- seq( from=0, to=50, by=2 )
#
days %>% 
    filter( walked == 0 ) %>% 
        ggplot( aes( x= missed_reason )) +
            geom_bar( color="black",
                      fill="red") +
             geom_text( stat='count', 
                        aes(label=..count..), vjust=-1) +
               xlab( "Reason for missing walk" ) +
               ylab( "Frequency" ) +
               theme(axis.text.x=element_text(angle = -90, hjust = 0))
#
```

## Weather conditions

```{r plot_bar_chart_weather}
#
weather_tabulation  <-                           # Count weather occurences
    days %>%  
        filter( !is.na( weather ) == 1 ) %>% 
            group_by( weather ) %>% 
                tally()
#
max_frequency <- max( weather_tabulation$n )    # Determine maxoccurences
#
days %>% 
    filter( !is.na( weather )) %>% 
    ggplot( aes( x = weather )) +
        geom_bar( color="black",
                  fill="blue") +
         geom_text( stat='count', 
                        aes(label=..count..), vjust=-1) +
        coord_cartesian(ylim = c(0, max_frequency + 2)) +
        xlab( "Weather") +
        ylab( "Frequency" ) +
        theme_cowplot() +
       theme(axis.text.x=element_text(angle = -90, hjust = 0))


```
 
## Routes walked 
 
```{r plot_routes_walked}
#
route_tabulation  <-                           # Count weather occurences
    days %>%  
        filter( !is.na( route ) == 1 ) %>% 
            group_by( route ) %>% 
                tally()
#
max_route <- max(route_tabulation$n )

days %>% 
    filter( walked == 1 ) %>% 
        ggplot(  aes( x = route) ) +
            geom_bar( color="black",
                      fill = "yellow") +            
            geom_text( stat='count', 
                        aes(label=..count..), vjust=-1) +
            coord_cartesian(ylim = c(0, max_route + 4)) +
            theme_cowplot() +
            theme(axis.text.x=element_text(angle = -90, hjust = 0))
#
```

### Instrumentation 

```{r plot_barchart_}

```








