---
title: "Walks Analysis: Categorical variables"
author: "by Craig W. Slinkman"
date: "July 23, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r load_functions}
#
source('~/R-Projects/Rsource/compute_dates_v004.R')        # To compute dates ...
source('functions/display_selected_days_v001.R')           # To d splay days  ...
#
```
 
 

```{r display_period, echo=FALSE}
#

format_date <-                                   # Function to format dates 
    function( unformated_date ){
        format( unformated_date, "%Y-%m%-%d" )
    } 
        
dates          <- compute_dates()                          # Compute dates ...
date_current   <- dates$date_000_days_ago                  # Access current date ...
#
```

```{r get_data}
#
file_path <- file.path( "data",                           # Set file path ...
                        "days_180.rds" ) 
#
load( file_path )                                         # Load days object ...
# 
```
 
 
### Display dFirst 10 observation inn last 180 days 

#### First 10 observations

```{r display_first_10}
#
first_10_days <- days_180[ 1:10, c(1,2,6:14)]         # Select first 10 days ...
#                                                     
display_selected_days( first_10_days )                # Display first 10 days 
#
```
 
 
#### Last 10 days of the last 180 days 

```{r display_last_10_days}
#
to <- dim( days_180 )[1]                      # Get subscript of last row...
from <- to - 10 + 1                           # Compute starting subscrupt of last
                                              # 10 rows ...
#
last_10_days <-                               # Get last 10 days ...
    days_180[ from:to, c(1,2,6:14)] 
#
display_selected_days( last_10_days )                 # Display as flextable ...
#
```
 
### Days walked and missed 

```{r plot_barchars_od Missed_walks and walks}
#
days <- 
    days_180 %>%                                 # Add capitalized variable   
       mutate( Walked = ifelse( walked == 0,     # labels for ggplot ....
                                "No", "Yes")) 
    
bins_count <-                                 # Count number of walks and no
    days %>%                                     # Mo walks
         count( Walked )                         

max_counts <- max( bins_count$n )                 # Determine max number of bin 
                                                 # bin count 

y_scale  <-  seq( from = 0, to = 180, by= 20 )    # Set breaks ...
y_labels = y_scale                                # Set labels ...
max_y    <- max_counts + 2                        # Set max y coordinate  


days %>% 
        ggplot( aes( x = Walked )) + 
        geom_bar( color="blue",
                      fill="yellow" ) +
        geom_text( stat='count', 
                       aes(label=..count..), vjust=-1) +
        scale_y_continuous( "Frequency",
                           breaks = y_scale,
                         labels= y_scale ) +
        coord_cartesian( ylim = c(0, max_y), 
                         expand = TRUE )

#
```


### Reasons for days without walks 

```{r draw_parchart_of_reasons_for_no_walks}
#
y_breaks <- seq( from = 0,                        # Set breaks and labels 
                 to = 50, 
                 by = 5 )      

no_walk_days <-                                     # keep only days with no walks ...
    days %>% 
        filter( walked == 0 )

bin_counts <-                                       # Count reasons for no walk
    no_walk_days %>%                                # days ...
        count( missed_reason )

max_count <- max( bin_counts$n )                    # Determin max bin count

#
no_walk_days %>% 
    filter( walked == 0 ) %>% 
        ggplot( aes( x= missed_reason )) +
            geom_bar( color="black",
                      fill="red") +
            geom_text( stat='count', 
                    aes(label=..count..), vjust=-1) +
            coord_cartesian( ylim = c(0, max_count + 2 ), 
                             expand = TRUE ) +
            xlab( "Reason for missing walk" ) +
            ylab( "Frequency" ) +
            theme(axis.text.x=element_text(angle = -90, hjust = 0))
#
```
 
 
## Weather conditions

```{r plot_bar_chart_weather}
#
library( cowplot )
#
weather_tabulation  <-                           # Count weather occurences
    days %>%  
        filter( !is.na( weather ) == 1 ) %>% 
            group_by( weather ) %>% 
                tally()
#
max_frequency <- max( weather_tabulation$n )    # Determine maxoccurences
#
days %>% 
    filter( !is.na( weather )) %>% 
    ggplot( aes( x = weather )) +
        geom_bar( color="black",
                  fill="blue") +
         geom_text( stat='count', 
                        aes(label=..count..), vjust=-1) +
        coord_cartesian(ylim = c(0, max_frequency + 2)) +
        xlab( "Weather") +
        ylab( "Frequency" ) +
        theme_cowplot() +
       theme(axis.text.x=element_text(angle = -90, hjust = 0))


```
 
## Routes walked 
 
```{r plot_routes_walked}
#
route_tabulation  <-                           # Count weather occurences
    days %>%  
        filter( !is.na( route ) == 1 ) %>% 
            group_by( route ) %>% 
                tally()
#
max_route <- max(route_tabulation$n )

days %>% 
    filter( walked == 1 ) %>% 
        ggplot(  aes( x = route) ) +
            geom_bar( color="black",
                      fill = "yellow") +            
            geom_text( stat='count', 
                        aes( label=..count.. ), vjust=-1) +
            coord_cartesian(ylim = c(0, max_route + 4)) +
            xlab( "Route" ) +
            theme_cowplot() +
            theme(axis.text.x=element_text(angle = -90, hjust = 0))
#
```

## Instrumentation 

```{r display_instrumentation}
#
walk_days <-                                    # Find all days where a walk 
    days_180 %>%                                # was taken ...
        filter( walked == 1 )

device_bin <-                                   # Tabulate bins by intrumentation ...
    walk_days %>% 
        count( device )
#
max_bin <- max( device_bin$n )                  # Detrmine maximum bin count
#
y_breaks <- seq( from = 0, 
               to   = max_bin,
               by = 25 )

walk_days %>% 
    ggplot( aes( x = device )) +
       geom_bar( color="black",
                 fill = "yellow") +            
            geom_text( stat='count', 
                        aes( label=..count.. ), vjust=-1) +
            coord_cartesian(ylim = c(0, max_bin + 5 )) +
            xlab( "Measure device" ) +
            theme_cowplot() +
            theme(axis.text.x=element_text(angle = -90, hjust = 0 ))
#       
```

### Shoes 


```{r display_shoes}
# 
shoe_bin <-                                    # Tabulate bins by shoes ...
    walk_days %>% 
        count( shoes )
#
max_count <- max( shoe_bin$n )              # Detrmine maximum bin count
#
y_breaks <- seq( from = 0, 
               to   = max_count+20,
               by = 25 )

walk_days %>% 
    ggplot( aes( x = shoes )) +
       geom_bar( color="black",
                 fill = "yellow") +            
            geom_text( stat='count', 
                        aes( label=..count.. ), vjust=-1) +
            coord_cartesian(ylim = c(0, max_bin + 20 )) +
            xlab( "Shoes" ) +
            theme_cowplot()
#  
```











