---
title: "Last 007 days walks"
author: "adopted by Craig W. Slinkman"
date: "6/16/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Introduction
This R-Markdown document lists the last 7 days walk activity and provides a summary of the last 7 days.

```{r load_packages, echo=FALSE}
###############################################################################
# We load necessary packages to supply needed functionality.
###############################################################################

suppressMessages(library(tidyverse))   # I live in the tidyverse ...
suppressMessages(library(tidyr))       # For additional data wrangling ...
suppressMessages(library(readxl))      # To read an xlsx spreadsheet ...
suppressMessages(library(lubridate))   # For advanced date processing ...
suppressMessages(library(formattable)) # To display formatted tibbles ...
suppressMessages(require(flextable))   # For reporting ...
suppressMessages(require(cowplot))     # For professional plots ...
suppressMessages(require(ggpubr))      # For professional plots ...
```

```{r set_rmarkdown_default_director}

###############################################################################
# Because eqach chunk resets the directory to the path that RMarkdown was 
# loaded from and the file path of this project is "D:\R-Projects\MyWalks" we
# need to globally chnge the directory. We do in the chunk below.
###############################################################################

md <- file.path( "D:/",
                 "R-Projects",
                 "MyWalks" )
knitr::opts_knit$set(root.dir = md )
```


```{r set_cowplot_to_default_theme}

###########################################################################
# We make cowplot the default theme for this document.
###########################################################################
theme_set( theme_cowplot )
```

```{r define_functions}
source('D:/R-Projects/MyWalks/functions/get_day_routes.R')
source('D:/R-Projects/MyWalks/functions/filter_by_days.R')
source('D:/R-Projects/MyWalks/functions/plot_walk_frequency.R')
source('D:/R-Projects/MyWalks/functions/compute_parametrics.R')
source('D:/R-Projects/MyWalks/functions/report_summary.R')
source('D:/R-Projects/MyWalks/functions/summarise_zones.R')
```

```{r read_data}
all_walks <- get_day_routes()
```

```{r keep_the_last_007_days_data}

############################################################################
# Determine the date of the first walk to be analysed.
############################################################################

first_date <- date( now()) - 7

############################################################################# Add plain date and chr_day for reporting.
###########################################################################

temp_tibble <-    
    all_walks  %>% 
        mutate( date = date( date_time ),
                chr_day = wday( date_time,
                                label = TRUE,
                                abbr = TRUE,
                                week_start = 
                                getOption("lubridate.week.start", 7)))


###########################################################################
# Sort id descending order ny date_time and select variables needed for 
# report.
############################################################################

last_007_days_walks <- 
    temp_tibble %>% 
        filter( date > first_date ) %>% 
            arrange( desc( date_time  )) 
                    
```

## Plot days activites

```{r plot_days_activities}

plot_walk_frequency( last_007_days_walks )

```



```{r summarize_last_007_days_walks}

############################################################################
# We compute the totals (when they make sense), the means, the standard
# deviations, the coefficient of variation, the skewness, and the kurosis
# of the basic walking statistics for the last 7 days walks.
###########################################################################

summary <- compute_parametrics( last_007_days_walks )
```

## Last seven days walks 

Note: The walks are sorted in reverse chronological order.  



```{r list_last_007_days}

   last_007_days_walks %>%
            select( date,
                    walked,
                    missed_reason,
                    route,
                    miles,
                    steps,
                    hours,
                    pace,
                    gain,
                    kcal,
                    avg_hr,
                    max_hr,
                    breaks,
                    stumbles, 
                    falls ) %>% 
                      flextable() %>% 
                        width( j = 1, 1.00 ) %>% 
                        width( j = c( 2, 4), 1.50 ) %>% 
                        width( j =4, 2.50 ) %>% 
                        colformat_num( j = c( 5:8 ),
                                   digits = 2,
                                   na_str = "" ) %>% 
                    colformat_num( j = c( 9, 10:13 ),
                                   digits = 0,
                                   na_str = "" ) %>% 
                   colformat_num(  j =10, 
                                   digits = 3,
                                   na_str = "" ) %>% 
                set_header_labels( date            = "Date",
                                    walked         = "Walked",
                                    missed_reason  = "Missed reason",
                                    route          = "Route",
                                    miles          = "Miles",
                                    steps          = "Steps(k)",
                                    hours          = "Hours",
                                    pace           = "Pace",
                                    gain           = "Gain",
                                    kcal           = "KCal",
                                    avg_hr         = "Mean\nHr",
                                    max_hr         = "Max\nHR",
                                    breaks         = "Breaks",
                                    stumbles       = "Stumbles",
                                    falls          = "Falls" ) %>%
                theme_zebra()
```

### Summary report

```{r_days_activties}

###########################################################################
# We create print the summary report here using flextable.
###########################################################################

report_summary(summary)
```
